### ISSUE TITLE
Incorrect filenaming

### ISSUE THREAD

**Issue by Ruriko** [catgirlfighter/nekopaw#324]
I don't know if it's the same for other sites but on nhentai it's naming files wrong with the latest version but in the previous version it names them correct. This is my filename format:
`C:\Users\Administrator\Downloads\doujin\33-36\%album_id%_%album:.150s%\$fnn:.3d$`

Instead of starting with 00 it starts with a random number like 44. In each folder it starts at a different number

**Comment by catgirlfighter** [comment]
That's weird. Don't remember I did any changes in naming.

**Comment by catgirlfighter** [comment]
Figured it. I believe some other resource have that issue, too (due to my laziness, for a most part). It happens when grabber can't make a name for a file during first phase (getting list). That's applies to nhetai now, too (due to a fact that album's page doesn't actually contain all pages). Made a change that doesn't allow a name generation until picture is already downloaded (so, counter doesn't trigger more than once).

**Comment by Ruriko** [comment]
thanks the latest update fixed the problem
